import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Components/Navbar";
import { Toaster } from "@/components/ui/sonner"; //A Shadcn Component
import { CartProvider } from "./context/CartContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cake App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white screen`}>
        <CartProvider>
           <Navbar/>
          {children}
          <Toaster className="bg-orange-400"/> {/* this is a shadcn componenent for the sonner component */}
        </CartProvider>
      </body>
    </html>
  );
}